### ISSUE TITLE
DLC maps not working

### ISSUE THREAD

**Issue by ForeskinJohn** [ineedbots/bo1_bot_warfare#1]
missing textures for DLC map icons, very slow loading upon starting a match on one, and CTD's.

**Comment by ForeskinJohn** [comment]
Is there perhaps a different method of loading the downloadable content with this mod?

**Comment by ineedbots** [comment]
The missing textures are caused by using the 'patch_mp.ff' and 'ui_patch_mp.ff' files. The ff's are supposed to contain the assets but don't, there isn't a way yet to extract materials from black ops pc ff files, and the mod tools are missing the dlc assets.
Using the regular patch_mp and ui_patch_mp will fix this

**Comment by eatitvidboi** [comment]
i dont really mind the issues with the DLC maps but I was curious to know if using the file replacement was safe regarding VAC. i assume its always off when i play combat training with the new ff files?

**Comment by ForeskinJohn** [comment]
> The missing textures are caused by using the 'patch_mp.ff' and 'ui_patch_mp.ff' files. The ff's are supposed to contain the assets but don't, there isn't a way yet to extract materials from black ops pc ff files, and the mod tools are missing the dlc assets.
> Using the regular patch_mp and ui_patch_mp will fix this

how do we go about saving stats in this case?

**Comment by ForeskinJohn** [comment]
im happy to report that with the latest update to this mod, the dlc maps are now fully playable albeit without actual textures for your minimap, but those arent need since you have markers for everything to begin with. thanks m8!
