### ISSUE TITLE
DLC mini maps are missing

### ISSUE THREAD

**Issue by koopa990** [ineedbots/bo1_bot_warfare#12]
The map preview from the map change menu are missing, so does the mini map during gameplay.

**Comment by CatiolaBR** [comment]
> The map preview from the map change menu are missing, so does the mini map during gameplay.

Mine too.. I dont know if it is with the game itself or only with the mod.   Im enjoying the mod to its fullest, but, on DLC content,  without the map hud, you kinda lose some of the game dynamism..

**Comment by ineedbots** [comment]
![image](https://github.com/ineedbots/t5_bot_warfare/assets/751729/e94a2966-bdda-4794-b302-2303808941ef)
![image](https://github.com/ineedbots/t5_bot_warfare/assets/751729/1981c38d-e73e-4bac-97b6-5faf31908c40)

This does not happen, If you are using the patch_mp, I do not support that anymore.
