### ISSUE TITLE
Not leveling up on bot warfare on my dedicated server

### ISSUE THREAD

**Issue by whatcorey** [ineedbots/bo1_bot_warfare#16]
Am i doing anything wrong? I have a plutonium server for bo1 with the mod bot warfare, but for some reason i am not leveling up

**Comment by snifflewhip** [comment]
Did you ever find a fix?

**Comment by gatallahx** [comment]
Make sure to copy `patch_mp.ff` and `patch_ui_mp.ff` from `/bo1bw111.zip/Others` into `/Call of Duty - Black Ops/zone/common`
When opening the game, do not select this mod as it should already be loaded in correctly

**Comment by ineedbots** [comment]
This isn't mod related, but client related. Plutonium will need to patch to make this work.  As a work around, do not set a `fs_game` and load the gscs by putting the files inside of `main_shared` folder in your game folder.
