### ISSUE TITLE
Level Up

### ISSUE THREAD

**Issue by AziGod** [ineedbots/bo1_bot_warfare#22]
Hey, I have install the mod in the correct folder in Appdata. But I have the same issue as someone else already said for keeping the level after the next game. I read the post and put the 2 .ff file in the zone folder where the original are to replace them but the mod isn't directly launch nor does the progression level stay. So I'm a little bit confused with the different folder and files to make it works.
Thanks if you have time to help me.

**Comment by Zapper762** [comment]
I am also having the same issue, latest version of plutonium, bo1, etc. Any fixes?

**Comment by AziGod** [comment]
I found a clear tutorial online and it works for me:
Okay, so I will try and make a step-by-step guide of how I have my setup working as of right now.

PRESTIGE IN COMBAT TRAINING WITH THE BLACK OPS 1 BOT WARFARE MOD

DISCLAIMER: THIS MOD INSTALLATION WILL PREVENT THE SERVER BROWSER FROM LOADING SERVERS WHILE IN USE, AND BREAKS MOST DLC MINIMAPS AND LOADING SCREENS (details on how to get servers back at the end of the installation guide)

1. Getting Started
	- Open your %localappdata% folder and find Plutonium (if you don't know how to do this, go to your Windows search bar in the bottom left and search Windows as this: %localappdata%
	- Go to "storage > t5 > zone", select both "patch_mp.ff" and "patch_ui_mp.ff", and copy them to your clipboard.
	- Do not close the folder once you have copied them, we will come back here later. Just minimize it for now. 
	- Make a folder on your desktop called "Patch Backups" or something similar and paste them inside. This is just to be safe. 
	- Next, go to this website and download the 1.1.1 version of the BO1 Bot Warfare mod:https://www.gamepressure.com/download.asp?ID=77587
	- Make sure to have a program that can unpack/extract .zip files (WinRAR, 7zip, etc.)

2. Placing Files and Extracting
	- With your mod downloaded, open up the "blackopsbotwarfare111.zip".
	- With the folders being visibile to you,  open your "Move to root of Black Ops folder" to see the files inside.
	- Click into the folders until you are in "Move to root of Black Ops folder > mods > mp_bots" and take the "mod.ff" file and place it in your minimized Plutonium T5 Zone folder with the other .ff  files already in it.
	- Now, we are going to backtrack a small bit so that we can finish placing the last two .ff files in Zone. Go back to where you can see "Move to root of Black Ops folder" and "Others".
	- Open the "Others" folder, copy both "patch_mp" and "patch_ui_mp" and paste them into your T5 Zone folder. It will ask if you want to replace the files in it already, so say yes (we already backed those up, so it's safe).
	- In your .zip file of the mod, go back one step outside of "Others" again. Click back into "Move to root of Black Ops folder" folder until you back at "Move to root of Black Ops folder > mods > mp_bots". Open the "mp_bots.iwd".
	- If your PC asks how you want to open it, select the same program you use to open .rar files.
	- Once opened, you will see a folder called "maps". Click through until you are at the path "mp_bots.iwd > maps > mp" and click into the "gametypes" folder.
	- Copy the .gsc file inside to your clipboard and tab back to your Plutonium zone folder.
	- Click back into T5 and then click into "scripts". Inside of this folder, create a new folder called "mp".
	- Once you are in the path "Plutonium > storage >t5 > scripts > mp", paste the .gsc file you have copied inside of it. 
	- Tab back to your mp_bots.iwd window and click back to where your path is "mp_bots.iwd > maps > mp".
	- Go into the "bots" folder and copy the three .gsc files inside to your clipboard.
	- Tab back to your "scripts > mp" folder that you just pasted the other .gsc in, and paste the files you just copied inside. There should now be 4 .gsc files total (assuming these files are the only script files you have added so far, you may have other scripts for different projects that you have played with).
	- You can now safely close the "mp_bots.iwd" and "blackopsbotwarfare111.zip" files.  

3. Making Sure Pluto Doesn't Override Your Patch Files
	- Navigate back to your Plutonium folder in "appdata". 
	- Open the "bin" folder and make a shortcut of the "plutonium-launcher-win32.exe" (not the bootstrapper).
	- Place your created shortcut somewhere you can access it (like the desktop), as this is what you will use now to open the Plutonium client.
	- Note that using this new shortcut stops the Plutonium client from downloading updates, as it is not launching Plutonium using the Updater, which I am sure is how most users (myself included) typically open Plutonium.
	- Test to make sure everything is working by using your new shortcut to open the launcher, and go launch T5 Multiplayer (either in LAN Mode or not).
	- Go to Combat Training and check your barracks/playercard to make sure that the Prestige option says "Available after completing level 50."

4. What to Do When Your Plutonium Needs to Update and Does Replace Your Patch Files
	- Plutonium can't go without updates for the rest of time because of this mod, so because of this, I will show you how to fix Combat Training Prestiging when you inevitably need to update.
	- After you update Plutonium, it will have downloaded and replaced the "patch_mp" file we are using from the mod back to the Plutonium original.
	- To fix this, all you need to do is go back to your "botwarfaremod111.zip", navigate back to the "patch_mp.ff" file, and paste it into the "zone" folder in Plutonium in the exact same way you did to install it the first time. 
	- That's it! You're done! Happy prestiging!

5. I Want to Play Online Again
	- Since replacing the "patch_mp.ff" file is what makes the mod works, it also breaks the server browser functionality of the game.
	- To restore the server browser functionality, simply open Plutonium through the Updater instead of the custom shortcut you created earlier.
	- Plutonium will update and place its own "patch_mp.ff" back inside of the "zone" folder, and you will be back to normal (Note that doing this is the same as updating Plutonium, obviously, so your Combat Training Prestige will not work unless you revisit Step 4).

**Comment by JGsouzaa** [comment]
Every time you open the plutonium you have to copy the two patch folders into %appdata% again with the plutonium open, I'm gonna open a issue to aware the team about this

**Comment by ineedbots** [comment]
this isn't mod related, but client related, please make requests to fix it on the client's end.
