### ISSUE TITLE
Theres any way to level up with this MOD?

### ISSUE THREAD

**Issue by FrankHz21** [ineedbots/bo1_bot_warfare#4]
I can level up without MOD and keep this obtained Level in the MOD, so far so good but when I play with mod I can´t level up 🤔
 I LOVE this mod, but has this problem.

**Comment by ineedbots** [comment]
The release package has a couple of .FF files,   replace the originals ( backup the originals ) and the mod will be loaded without needing to select it in the mods menu,     and you should be able to rank up doing this

**Comment by FrankHz21** [comment]
> The release package has a couple of .FF files, replace the originals ( backup the originals ) and the mod will be loaded without needing to select it in the mods menu, and you should be able to rank up doing this

WOW thanks! It works, has a bug minimap in some DLC maps but works fine.

**Comment by zhm86** [comment]
If you just want to unlockall, here are steps:
Launch the game, do not load the mod, go to "PLAY - COMBAT TRAINING"
Press "~" to open the console, type "unlockall", you will be max leveled in combat training, and the stat is saved.
Back to the main menu, load the mp_bot and enjoy.
