### ISSUE TITLE
Can you rank up in combat training?

### ISSUE THREAD

**Issue by syaifulnizamyahya** [ineedbots/bo1_bot_warfare#5]
When I play this mod, I was stuck at level 2. Does it suppose to happen like this? How can i rank up? Where should I put files in Others folder?

**Comment by syaifulnizamyahya** [comment]
I think, the installation instruction should be updated. T5m and Steam seems to have different installation method.

**Comment by Eshyyyyy** [comment]
I can't level up either, challenges and XP are basically frozen, and you don't get any from kills/completing challenges. Challenges will say they've been completed but will not actually complete, and will just spam when you meet the requirement each time.

**Comment by rknissi** [comment]
> 
> 
> When I play this mod, I was stuck at level 2. Does it suppose to happen like this? How can i rank up? Where should I put files in Others folder?

You can overwrite these files in the 'Zone/Common' folder (backup the originals).
The author said it [here](https://www.moddb.com/mods/bot-warfare/downloads/bo1-bot-warfare-110). This way you will be able to rank up while playing Combat Training.

> 
> 
> I can't level up either, challenges and XP are basically frozen, and you don't get any from kills/completing challenges. Challenges will say they've been completed but will not actually complete, and will just spam when you meet the requirement each time.

If you use the same fix, you should be able to level up while playing with bots. Just put the 2 files from the "Others" folder ('patch_mp.ff' and 'patch_ui_mp.ff') to Zone/Common folder (make sure to back up those files)

**Comment by gensxi** [comment]
I moved the 'patch_mp.ff' and 'patch_ui_mp.ff' files over to Zone/Common and I can level up but I can't earn any COD Points and when I buy something I don't lose any Points, they just stay the same. Does anybody have a fix for this?

**Comment by ineedbots** [comment]
Using the modified patch_mp will allow you to use the mod with ranking up.

But the ff isn't perfect. A won't fix imo, seeing the RektT5 allows you to load a mod with rank up.
