### ISSUE TITLE
Double options for amount of aalies and enemies bots

### ISSUE THREAD

**Issue by rknissi** [ineedbots/bo1_bot_warfare#6]
![Blackops](https://user-images.githubusercontent.com/12503765/132962356-23596113-a846-4635-a60d-f73aefaf328e.png)

When editing the Combat Training Options, there's actually 2 configs to set the amount of both Players alllies and enemies. It seems that the game responds to the first option of each category.

**Comment by rknissi** [comment]
Just noticed that these settings are located in both [here](https://github.com/ineedbots/bo1_bot_warfare/blob/master/mods/mp_bots/ui_mp/custom_game_create.menu#L687-L715) and [here](https://github.com/ineedbots/bo1_bot_warfare/blob/79c0dcf7acc650c5795b1d5771c1bf1ffbe63b0a/mods/patch_mp/ui_mp/custom_game_create.menu#L687-L713).

From what I've noticed, these settings are just being used to increase the player count [here](https://github.com/ineedbots/bo1_bot_warfare/blob/79c0dcf7acc650c5795b1d5771c1bf1ffbe63b0a/mods/mp_bots/maps/mp/gametypes/_bot.gsc#L186-L190) from the previous maximum: 11.


How about changing the title and description of those new settings like [here](https://github.com/ineedbots/bo1_bot_warfare/blob/79c0dcf7acc650c5795b1d5771c1bf1ffbe63b0a/mods/patch_mp/ui_mp/custom_game_create.menu#L729-L734)?

Another solution could be just using this new settings to set the allies and enemies count? Like:

```
        //bot_friends = GetDvarInt( #"bot_friends" );
	//bot_enemies = GetDvarInt( #"bot_enemies" );
	
        bot_enemies = GetDvarInt("bot_enemies_extra");
	bot_friends = GetDvarInt("bot_friends_extra");
```



I don't have any experience in modding, so it's a possibility that I said something wrong.

**Comment by ineedbots** [comment]
menus could be improved to make it use only 1 value,
but a wontfix imo

basically, the actual value will be the 2 values added together


this was the solution used to get around the 9 player limitation on the bot_friends dvar
