### ISSUE TITLE
DLC Maps Loading screen/radar just blocks

### ISSUE THREAD

**Issue by LevelChecker** [ineedbots/bo1_bot_warfare#7]
The minimap/radar are shown as just grey blocks as if it cannot be loaded if you use the Patch mp files included, however these files are needed to use on a dedicated server, is there any way to get them to work with the dlc map graphic/minimaps working?

**Comment by ineedbots** [comment]
needs a better solution for using patch_mp.ff

**Comment by ineedbots** [comment]
dupe of #5
