### ISSUE TITLE
Unable to give bots random rank

### ISSUE THREAD

**Issue by whatcorey** [ineedbots/bo1_bot_warfare#8]
Because the mod auto loads itself after installing the patch.ff files, if you edited the bots.gsc to "loadout_rank 0" which gives bots a random rank, it will not work because the mod is not loaded properly through the mod menu, rather being loaded automatically. I have not found a fix for this yet.

**Comment by LeRutY** [comment]
pt6 (Black Ops 2 Plutonium) has the same issue . Worst is you can´t adjust the bot difficulty settings to your liking which is needed for BO2, no idea if it´s working in BO1, that one has acceptable bots

Start a match, open the console and type in "/bots_loadout_rank 0" and then "map_restart". I think the value is saved for the whole session

**Comment by ineedbots** [comment]
correct, you use the dvar.

you would have to rebuild the mod when you edit any of the files.

**Comment by whatcorey** [comment]
> pt6 (Black Ops 2 Plutonium) has the same issue . Worst is you can´t adjust the bot difficulty settings to your liking which is needed for BO2, no idea if it´s working in BO1, that one has acceptable bots
> 
> Start a match, open the console and type in "/bots_loadout_rank 0" and then "map_restart". I think the value is saved for the whole session

Nope. that does not work, if you start a match even in private match, and you try that cvar, it will say "unknown cmd" every single time, so, the cvar does not work at all

**Comment by whatcorey** [comment]
so what do i edit in the mod to give them a random rank?
